Site-statique/config/routes.rb
Rails.application.routes.draw do
  get '/', to: 'static_pages#home', as: "home"

  get '/contact', to: 'static_pages#contact', as: "contact"

  get '/about', to: 'static_pages#about', as: "about"

  get '/riana', to: 'static_pages#about_riana', as: "aproposriana"

  get '/cedric', to: 'static_pages#about_cedric', as: "aproposcedric"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Site-statique/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def contact
  end

  def about
  end
  
  def about_riana
  end
  
  def about_cedric
  end
end

Site-statique/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>JeMePresente</title>
	<%= csrf_meta_tags %>

	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>
	<style>
		body{
			background: url(https://3.bp.blogspot.com/-entRXOuLLas/Vw9EIE1EJtI/AAAAAAAAAvY/dTcLZUsNpww/s000/background.jpg) fixed center -120px;
			background-image: url("https://3.bp.blogspot.com/-entRXOuLLas/Vw9EIE1EJtI/AAAAAAAAAvY/dTcLZUsNpww/s000/background.jpg");
		}
		</style>
</head>

<body>
	<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>

		<div class="collapse navbar-collapse" id="navbarSupportedContent">
			<ul class="navbar-nav mr-auto">
				<li class="nav-item active">
					<a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="contact">Contact</a>
				</li>
				<li class="nav-item dropdown">
					<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
						About
					</a>
					<div class="dropdown-menu" aria-labelledby="navbarDropdown">
						<a class="dropdown-item" href="/riana">About Riana</a>
						<a class="dropdown-item" href="/cedric">About Cédric</a>
					</div>
				</li>

			</ul>	
		</div>

	</nav>
	<%= yield %>
</body>
</html>

Site-statique/app/views/static_pages/about.html.erb
<h1></h1>

<p> En fait nous sommes deux:</p>

<a href = "<%= aproposcedric_path %>" > about Cedric </a> <br> <br>
<a href = "<%= aproposriana_path %>" > about Riana </a>

Site-statique/app/views/static_pages/about_cedric.html.erb
<center class="card" style="width: 18rem; margin: 0 auto;">
  <img class="card-img-top" src="https://lh3.googleusercontent.com/czfZwb1uVWVO0YuHt0mK-P7CQSA3ckghjuo7uVNI-KMVZYUtAot94UNnhKfKPHscWf6YvNTmjyZx=w542-h544-no">
  <div class="card-body">
    <p class="card-text">Je suis Cédric
    	<ul>
    		<li>Sur slack : @Cédric</li>
    		<li>Equipe de Madagascar</li>
    	</ul></p>
  </div>
</center>

Site-statique/app/views/static_pages/about_riana.html.erb
<center class="card" style="width: 18rem; margin: 0 auto;">
  <img class="card-img-top" src="https://scontent.ftnr2-1.fna.fbcdn.net/v/t1.0-9/30728653_451705565247445_8041631640994185216_n.jpg?_nc_cat=0&oh=ceb88acff2f56c6f81563e3acb9b31ac&oe=5B65D52F" alt="Card image cap">
  <div class="card-body">
    <p class="card-text">Je suis RianaRC
    	<ul>
    		<li>Sur slack : @RianaRC</li>
    		<li>Equipe de Madagascar</li>
    	</ul></p>
  </div>
</center>

Site-statique/app/views/static_pages/contact.html.erb
<table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">#</th>
      <th scope="col">Nom</th>
      <th scope="col">Github</th>
      <th scope="col">Sur Slack</th>
    </tr>
  </thead>
  <tbody  style="background-color: #fffc;">
    <tr>
      <th scope="row">1</th>
      <td>Riana</td>
      <td>https://github.com/RianaRC</td>
      <td>@RianaRC</td>
    </tr>
    <tr>
      <th scope="row">2</th>
      <td>Cédric</td>
      <td>https://github.com/Tafitasoa</td>
      <td>@Cédric</td>
    </tr>
  </tbody>
</table>



<!--
<div>
	<h2> Bienvenue dans le page des contacts </h2>
	<p> RianaRC (sur Slack: @Riana) </p>
	<p> Tafitasoa Cédric (sur Slack: @Cédric ) </p>
</div>

<a href = "<%=home_path%>" > Home </a>
-->

Site-statique/app/views/static_pages/home.html.erb
<div class="container">

	<div class="p-3 mb-2 bg-primary text-white">
		<h1 >Bienvenue sur notre premier site rails</h1>
	</div>
	
	<center style="color:#fff">
		<h3>Pair-programming de <strong>Riana</strong> et <strong>Cédric</strong></h3>
	</center> 
</div>