projet_avec_backend/config/routes.rb
Rails.application.routes.draw do
  get '/creation(/:erreur)', to: 'users_controller#new', as: 'creation'
  
  post '/', to: 'users_controller#create' 

  get '/', to: 'static_pages#home' 

  get '/user/id_de_l\'utilisateur', to: 'users_controller#show'

  get '/user/:username', to: 'users_controller#every_user'

  get '/liste', to: 'users_controller#list', as: 'list'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

projet_avec_backend/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

projet_avec_backend/app/models/user.rb
class User < ApplicationRecord
  validates :username, uniqueness:true 
end

projet_avec_backend/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

projet_avec_backend/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

projet_avec_backend/app/controllers/users_controller_controller.rb
class UsersControllerController < ApplicationController
  def new
    @msg = params[:erreur]
  end

  def every_user
    if params['username'].to_i == 0
      @user = User.find_by(username: params['username'].capitalize)
    else
      @user = User.find_by(id: params['username'])
    end
  end

  def create
    user = User.new
    message = "Username invalid(deja pris ou comportant d'espace)"
    if !params["username"].match(/\s/)
      user.username = params["username"].capitalize
      user.bio = params["bio"]
      user.save
      validation = user.valid?
        if validation
          redirect_to "/user/#{user.id}"
        else 
        redirect_to "/creation/#{message}"
       end
    else
      redirect_to "/creation/#{message}"
    end
  end

  def list
    @list = User.all
  end

end

projet_avec_backend/app/helpers/application_helper.rb
module ApplicationHelper
end

projet_avec_backend/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

projet_avec_backend/app/helpers/users_controller_helper.rb
module UsersControllerHelper
end

projet_avec_backend/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProjetAvecBackend</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

projet_avec_backend/app/views/static_pages/home.html.erb
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css"/>

<center>

<div style="position:relative;top:200px;">
<h1>Hello</h1>
<h1>Bienvenue sur ma page d accueil </h1>

<a href = "<%=creation_path%>" > Creer nouveau User </a> <br>
<a href = "<%=list_path%>" > Voir la liste </a>
</div>  

</center>

projet_avec_backend/app/views/users_controller/every_user.html.erb
<center>
<h1> Bienvenue <%= @user.username%> </h1>
<p> Voila ton bio: <em>  <%= @user.bio %> </em> </p>
<a href="/" > Home </a>
</center>

projet_avec_backend/app/views/users_controller/list.html.erb
<h1> Voici la liste des utilisateurs presents dans la base de donnée </h1>
<h2> Au debut, la liste est vide! ;) vas-y et crée des utilisateurs </h2>

<% for i in 0...@list.length do %>
  <p> Son nom: <%= @list[i].username %>  </br> Et voila son bio: <%=@list[i].bio %>  </p>
<% end %>

<a href="/" > Home </a>

projet_avec_backend/app/views/users_controller/new.html.erb
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css"/>

<div style="position:relative;top:80px;">
<center>
<h3> <%= @msg %>  </h3>
<h1> Bienvenue dans la création de nouveau utilisateur</h1> <br> <br>


<form action="/" method="post" >
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>" >
    Le prénom du nouveau User: <br> 
    <input type="text" name="username"><br><br>
    Editez son bio: <br>
    <textarea name="bio"
    rows="3" cols="50">
    </textarea> <br><br>
    <input  type="submit" name="Envoyer">

</form>

<br><br>
<a href="/" > Home </a>

</center>
</div>